### ISSUE TITLE
user stories complete

### ISSUE THREAD

**Issue by melhuang** [melhuang/TweetTweet#1]
please review /cc @codepathreview @codepath 💃

**Comment by codepathreview** [comment]
:+1: nice work. A few notes after checking out the code:
- Good to see you were able to format the timestamp cleanly
- Good to see you refreshed the timeline after composing a new tweet
- Glad to see you made the compose activity into a dialog instead
- Good job using RecyclerView
- Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out
- Consider adding ActiveAndroid to the Tweet and User. See the [persistence guide](https://github.com/thecodepath/android_guides/wiki/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](https://github.com/thecodepath/android_guides/wiki/ActiveAndroid-Guide) for more details.
- Consider [better organizing your source files](http://guides.codepath.com/android/Organizing-your-Source-Files)

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
